### ISSUE TITLE
Stolen

### ISSUE THREAD

**Issue by Logan7432** [dinhduynhat/Agar-Ogar-Cigar-web-client#4]
This Agario web-client is stolen from me, I never got asked for you to use my custom coded site.

**Comment by plazo123** [comment]
logan hi i feel bad for you whats your site ??

**Comment by Logan7432** [comment]
@plazo123 I don't run my site anymore;(

**Comment by plazo123** [comment]
why ?

**Comment by plazo123** [comment]
you want to run it on my server i dont mind

**Comment by Logan7432** [comment]
@plazo123 Too much work, Thanks for offer but im not into agario at the moment and pretty busy. Thanks A lot though!

**Comment by dinhduynhat** [comment]
check this : https://github.com/dinhduynhat/Agarvn
